### ISSUE TITLE
Can't install (erors)

### ISSUE THREAD

**Issue by Sogl** [CosmoCMS/Cosmo#286]
I use WAMP OpenServer.

First of all, in install.php:
Error: File core/app/autoload.php permissions are not set to 777. Please change them and refresh.

I login as administrator in Windows 8.1 x64. What 777 it wants?

Second, if I leave password field empty (local development), in autoload.php:
$password = 'undefined';

'undefined' not equal ''

In summary DB not create and I see error:
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1049] Unknown database 'cosmo'' in C:\OpenServer\domains\cosmo\core\app\autoload.php:12 Stack trace: #0 C:\OpenServer\domains\cosmo\core\app\autoload.php(12): PDO->__construct('mysql:host=loca...', 'root', '') #1 C:\OpenServer\domains\cosmo\core\app\initialize.php(3): require_once('C:\\OpenServer\\d...') #2 C:\OpenServer\domains\cosmo\index.php(1): include('C:\\OpenServer\\d...') #3 {main} thrown in C:\OpenServer\domains\cosmo\core\app\autoload.php on line 12

p.s. Please, add link to install.php in main page.

**Comment by James-Dunn** [comment]
The error is about the file permissions, not the user's.

I believe the undefined issue will be fixed in beta 3.

**Comment by Sogl** [comment]
But how to install in this beta?

**Comment by James-Dunn** [comment]
This issue should be fixed in version beta 3, released today. Download that version and try.

**Comment by Sogl** [comment]
Nothing changed....
Problem NOT solved. 

Try to install beta 3 without password:
$password = 'undefined';

**Comment by Sogl** [comment]
Also if you create user for mySQL, you got next error:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1049] Unknown database 'cosmo'' in C:\OpenServer\domains\cosmo\core\app\autoload.php:12 Stack trace: #0 C:\OpenServer\domains\cosmo\core\app\autoload.php(12): PDO->__construct('mysql:host=loca...', 'cosmo', '1') #1 C:\OpenServer\domains\cosmo\install.php(56): include('C:\\OpenServer\\d...') #2 {main} thrown in C:\OpenServer\domains\cosmo\core\app\autoload.php on line 12

**Comment by James-Dunn** [comment]
Couldn't duplicate the issue. You can manually delete the "undefined" so it's just an empty '' from the core/app/autoload.php file and try that.

**Comment by Sogl** [comment]
>Couldn't duplicate the issue.
Just leave password field empty.

>You can manually delete the "undefined" so it's just an empty '' from the core/app/autoload.php file >and try that.
It not helps because DB can't installed in this step! 
DB installs only if you fix errors. That's why I created new user with password in MySQL.

Now I have everything working, but it is not obvious steps for the new user.

**Comment by James-Dunn** [comment]
I tried leaving the password empty, but it just puts a blank string in the configuration file, not undefined. The instal file checks to make sure there is a value in each field to check against that.

**Comment by James-Dunn** [comment]
I think I found what caused your issue. Should be fixed in beta.4

**Comment by oomlaut** [comment]
I also am receiving this message 

> There was an error installing Cosmo.

> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /home/[PATH REDACTED]/core/app/autoload.php:12 Stack trace: #0 /home/[PATH REDACTED]/core/app/autoload.php(12): PDO->__construct('mysql:host=loca...', [USER REDACTED]', '[PASSWORD REACTED]') #1 /home/[PATH REDACTED]/install.php(57): include('/home/[PATH REDACTED]...') #2 {main} thrown in /home/[PATH REDACTED]/core/app/autoload.php on line 12

Looking into the `autoload.php` file, it appears that it did not accept and write in the correct value for $host; it remains _localhost_
